hyperparams:
  extractor: {}
  selector: {}
  regressor:
    n_estimators: 100
    max_depth: null

data:
  filepath: ./timeseries.csv

metrics:
  - name: mean absolute error
    params: {}

search:
  jobs: -1
  grid:
    extractor: {}
    selector: {}
    regressor:
      n_estimators: [100]
      max_depth: [5,10,30,10]

export:
  output_dir: ./models

reports:
  dir: ./reports